In [2]:
# Creating an array

# 1-D array
import numpy as np
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.ndim
#Gives the dimention

1

In [5]:
#Shape
a.shape

(6,)

In [6]:
len(a)

6

In [9]:
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [13]:
len(b) #returns the size of the first dimension

2

In [18]:
c = np.array([[[0,1],[2,3]],[[8,9],[10,11]]])
c #3-D array

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]]])

In [19]:
c.ndim

3

In [20]:
c.shape

(2, 2, 2)

In [21]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b = np.arange(1,10,2) #start, end (exclusive), step
b

array([1, 3, 5, 7, 9])

In [25]:
a = np.linspace(0, 1, 6) #start, end , numer of points
a    

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
c = np.eye(3) #Returns a 2-dimensional identity matrix
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])