In [2]:
#Copies and Views
import numpy as np

a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
# Slicing (Just like normal python list)
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [4]:
np.shares_memory(a, b) # Numpy shares memory since it uses memory management

True

In [5]:
b[0] = 10

In [6]:
b

array([10,  2,  4,  6,  8])

In [7]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8])

In [8]:
#Changing b array also changes a array

In [9]:
# If you dont want this to happen you can use .copy() instead

a = np.arange(10)
c = a[::2].copy()

In [10]:
c

array([0, 2, 4, 6, 8])

In [12]:
np.shares_memory(a, c)

False

In [13]:
c[0] = 10

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
c

array([10,  2,  4,  6,  8])

In [16]:
#Fancy Indexing

a = np.random.randint(0,20,15)

In [17]:
a

array([16, 17,  7,  0,  8,  4, 13,  1,  8, 11, 16, 19, 17, 17,  4])

In [19]:
mask = (a %2 ==0)

extract_from_a = a[mask]
extract_from_a

array([16,  0,  8,  4,  8, 16,  4])

In [20]:
a[mask] = -1
a

array([-1, 17,  7, -1, -1, -1, 13,  1, -1, 11, -1, 19, 17, 17, -1])