In [1]:
#Create a diagonal matrix using numpy arrays

import numpy as np

# Create a 3x3 diagonal matrix with elements 1, 2, and 3

diagonal_matrix = np.diag([1, 2, 3])

diagonal_matrix

# Output:

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [2]:
np.diag(diagonal_matrix) #extract diagonal elements

array([1, 2, 3])

In [3]:
# create a random element array

random_array = np.random.rand(3)

random_array

# Output:

array([0.41127049, 0.32518113, 0.80151432])

In [6]:
#2 Basic Data types
a = np.arange(10)

a.dtype

dtype('int32')

In [10]:
a = np.arange(10,dtype='float64')
a.dtype

dtype('float64')

In [11]:
# Other data types

d = np.array([1+2j, 2+4j])
d.dtype

dtype('complex128')

In [14]:
b = np.array([False,True])
b.dtype

dtype('bool')