In [1]:
import numpy as np


In [2]:
#With scalars
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a+1

array([2, 3, 4, 5, 6])

In [4]:
a*2

array([ 2,  4,  6,  8, 10])

In [5]:
a**2

array([ 1,  4,  9, 16, 25])

In [9]:
b = np.ones(5)+1
b

array([2., 2., 2., 2., 2.])

In [10]:
a-b #Matrix substrations


array([-1.,  0.,  1.,  2.,  3.])

In [11]:
a*b

array([ 2.,  4.,  6.,  8., 10.])

In [15]:
# Matrix multiplication

c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])
print(c@d)
print("********************************")
print(c.dot(d))

[[19 22]
 [43 50]]
********************************
[[19 22]
 [43 50]]


In [16]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
a == b

array([ True,  True,  True,  True,  True])

In [17]:
a = np.array([1,3,4,4,5])
b = np.array([1,2,3,5,5])
a == b

array([ True, False, False, False,  True])

In [18]:
a > b

array([False,  True,  True, False, False])

In [19]:
np.array_equal(a, b)

False

In [25]:
#Transcendental function

a = np.arange(5)

In [26]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [27]:
np.log(a)

C:\Users\birat\AppData\Local\Temp\ipykernel_6532\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [28]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

10